[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
fix = true
select = ["E","F","W","I","N","B","UP","PT","RET"]
ignore = ["E203","E266","E501"]  # E501 перекрывает black по длине строки; при желании убери
exclude = ["venv",".venv",".git","__pycache__"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true

[tool.pylance]
typeCheckingMode = "basic"
reportOptionalMemberAccess = false
reportOptionalSubscript = false
reportGeneralTypeIssues = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]
norecursedirs = ["tests/archived", "tests/__pycache__"]
